# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# host=${{ secrets.TENCENT_HOST }}; username=${{ secrets.TENCENT_USERNAME }}; password= ${{ secrets.TENCENT_PASSWORD }}; port= ${{ secrets.TENCENT_PORT }};
name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: SCP FILES
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}
          port: ${{ secrets.TENCENT_PORT }}
          source: "webSource/"
          target: "/home/lighthouse/local-source/"
